apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aghome

resources:
  - namespace.yaml
  - pvc-config.yaml
  - pvc-work.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - route.yaml

configMapGenerator:
  - name: aghome-config
    files:
      - AdGuardHome.yaml
