apiVersion: apps/v1
kind: Deployment
metadata:
  name: arr
  namespace: arr
  labels:
    app: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arr
  template:
    metadata:
      labels:
        app: arr
    spec:
      initContainers:
        - name: gluetun
          restartPolicy: Always
          image: docker.io/qmcgaw/gluetun:v3.41.0
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - MKNOD
          env:
            - name: "TZ"
              value: "Europe/Berlin"
            - name: "VPN_SERVICE_PROVIDER"
              value: "protonvpn"
            - name: "VPN_TYPE"
              value: "wireguard"
            - name: "WIREGUARD_PRIVATE_KEY"
              valueFrom:
                secretKeyRef:
                  name: protonvpn
                  key: wireguard_private_key
            - name: "SECURE_CORE_ONLY"
              value: "on"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.96.0.0/12"
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:5.1.4
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: webui
              containerPort: 8080
              protocol: TCP
            # - name: torrent
            #   containerPort: 6881
            #   protocol: TCP
            # - name: torrent-udp
            #   containerPort: 6881
            #   protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        - name: nzbget
          image: lscr.io/linuxserver/nzbget:26.0.20260206
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: nzbget
              containerPort: 6789
              protocol: TCP
          volumeMounts:
            - name: nzbget-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: prowlarr
              containerPort: 9696
              protocol: TCP
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr:4.0.16
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: sonarr
              containerPort: 8989
              protocol: TCP
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: tv-shows
              mountPath: /tv
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: radarr
              containerPort: 7878
              protocol: TCP
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: movies
              mountPath: /movies
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:3.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: lidarr
              containerPort: 8686
              protocol: TCP
          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: music
              mountPath: /music
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:1.5.5
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: bazarr
              containerPort: 6767
              protocol: TCP
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: tv-shows
              mountPath: /tv
            - name: movies
              mountPath: /movies
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: flaresolverr
              containerPort: 8191
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: nzbget-config
          persistentVolumeClaim:
            claimName: nzbget-config-pvc
        - name: downloads
          hostPath:
            path: "/mnt/data/downloads"
            type: Directory
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: lidarr-config-pvc
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
        - name: tv-shows
          hostPath:
            path: "/mnt/data/media/tvshows"
            type: Directory
        - name: movies
          hostPath:
            path: "/mnt/data/media/movies"
            type: Directory
        - name: music
          hostPath:
            path: "/mnt/data/media/music"
            type: Directory
