apiVersion: apps/v1
kind: Deployment
metadata:
  name: teruko
  namespace: teruko
  labels:
    app: teruko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teruko
  template:
    metadata:
      labels:
        app: teruko
    spec:
      containers:
        - name: teruko
          image: registry.licht/teruko-svelte:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: DATABASE_URL
              value: "file:/data/teruko.db"
            - name: IMG_FOLDER
              value: "/data/teruko"
            - name: BODY_SIZE_LIMIT
              value: "Infinity"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: http
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: teruko
              mountPath: /data
      volumes:
        - name: teruko
          hostPath:
            path: /mnt/data/teruko
            type: Directory
