apiVersion: v1
kind: Service
metadata:
  name: teruko
  namespace: teruko
  labels:
    app: teruko
spec:
  selector:
    app: teruko
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
  type: ClusterIP
