apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: unbound
  labels:
    app: unbound
spec:
  selector:
    app: unbound
  ports:
  - name: dns-udp
    port: 53
    targetPort: 5353
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: 5353
    protocol: TCP
  type: ClusterIP
