apiVersion: v1
kind: Service
metadata:
  name: hono
  namespace: hono
  labels:
    app: hono
spec:
  selector:
    app: hono
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
  type: ClusterIP
